# Generated by Django 4.0.3 on 2022-03-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='receive_currency',
            field=models.CharField(max_length=10),
        ),
    ]
